backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "uploads"

collections:
  - name: "pubs"
    label: "Publicaciones"
    folder: "src/content/blog"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
