backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Publicaciones"
    folder: "/src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Títol", name: "title", widget: "string" }
      - { label: "Descripcio", name: "description", widget: "text" }
      - { label: "Data de publicació", name: "pubDate", widget: "datetime" }
      - { label: "Imatge de portada", name: "coverImage", widget: "image" }
      - { label: "Contingut", name: "body", widget: "markdown" }

  - name: "cover"
    label: "Portades"
    folder: "/src/content/cover"
    create: true
    fields:
      - { label: "Títol", name: "title", widget: "string" }
      - { label: "Imatge", name: "coverImage", widget: "image" }

  - name: "highlight"
    label: "Destacats"
    folder: "/src/content/highlight"
    create: true
    fields:
      - { label: "Títol", name: "title", widget: "string" }
      - { label: "Enllaç", name: "link", widget: "string" }
